import { NextRequest, NextResponse } from "next/server";
import Groq from "groq-sdk";

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

export async function POST(req: NextRequest) {
  try {
    const { projectDescription, conversation } = await req.json();

    const newConversation = [
      ...conversation,
      {
        role: "user",
        content: projectDescription,
      },
    ];

    const response = await groq.chat.completions.create({
      messages: [
        {
          role: "system",
          content: `
            You are an AI that generates high-quality README files in markdown format. The README should be well-structured and comprehensive, including the following sections:

                Title
                Description
                Installation Instructions
                Usage
                Features
                Contributing
                License
                Contact Information

            Ensure that the README is professional, easy to read, and includes relevant examples where necessary.

            Based on the context provided, generate the best possible README file. If the context is incomplete, infer missing details to the best of your ability and focus on creating a comprehensive and clear README file. The main goal is to deliver a high-quality README in markdown format that effectively communicates the purpose and usage of the project.

            The README content should start directly with the title and should not include any preamble or extraneous text before the README content. At the end of the README, include the line: "Generated by EmpyreanUI README.md".
          `,
        },
        ...newConversation,
      ],
      model: "gemma2-9b-it",
      temperature: 0.7,
      max_tokens: 1024,
      top_p: 1,
      stream: false,
    });

    return NextResponse.json({
      readme: response.choices[0]?.message?.content || "",
    });
  } catch (error) {
    console.error("Error generating README:", error);
    return NextResponse.json(
      { message: "Failed to generate README" },
      { status: 500 }
    );
  }
}
