const prompts: string[] = [
  "Generate a comprehensive README for an e-commerce website. Include the following sections:\n1. **Project Purpose**: Briefly describe the main goals and objectives of the project.\n2. **Main Features**: Highlight key features and functionalities of the website.\n3. **Tech Stack**: List the technologies used, such as React, Node.js, and MongoDB.\n4. **Installation Steps**: Provide detailed instructions on how to set up the project locally.\n5. **Contribution Guide**: Explain how others can contribute to the project, including guidelines and best practices.",
  "Create a README for a machine learning project with the following sections:\n1. **Project Overview**: Describe the problem the project aims to solve and its significance.\n2. **Datasets Used**: List and briefly describe the datasets used in the project.\n3. **ML Models Implemented**: Provide details about the machine learning models used, including algorithms and architectures.\n4. **Setup Instructions**: Explain the setup process, including dependencies and environment configuration.\n5. **Running Experiments**: Provide instructions on how to run experiments and reproduce the results.",
  "Write a README for a React Native mobile app. Include the following sections:\n1. **App Purpose**: Explain the main purpose and target audience of the app.\n2. **Core Features**: List and describe the main features of the app.\n3. **Installation Instructions**: Provide step-by-step instructions for setting up the app on both iOS and Android.\n4. **Development Environment**: Explain how to set up the development environment.\n5. **Running the App Locally**: Include instructions for running the app on a local device or simulator.",
  "Generate a README for a personal portfolio website. Include the following sections:\n1. **Goal**: Describe the purpose of the website, such as showcasing personal projects, skills, and experience.\n2. **Technologies Used**: List the technologies used, such as Next.js and Tailwind CSS.\n3. **Local Setup**: Provide steps for setting up the project locally.\n4. **Customization**: Explain how to customize the website to add personal information and projects.",
  "Create a README for a Node.js API project. Include the following sections:\n1. **API Functionality**: Describe the main functionality of the API.\n2. **Endpoints**: List and describe the available endpoints, including request and response formats.\n3. **Development Environment Setup**: Provide instructions for setting up the development environment.\n4. **Usage Examples**: Include examples of how to use the API.\n5. **Authentication Methods**: Explain the authentication methods used.\n6. **Running Tests**: Provide instructions for running tests.",
  "Write a README for a Python data analysis project. Include the following sections:\n1. **Project Objectives**: Describe the main objectives of the project.\n2. **Data Sources**: List and describe the data sources used.\n3. **Analysis Methods**: Provide an overview of the analysis methods and techniques used.\n4. **Required Libraries**: List the required libraries and dependencies.\n5. **Setup Steps**: Provide detailed setup instructions.\n6. **Reproducing Results**: Explain how to reproduce the analysis results.",
  "Generate a README for a Next.js blog site. Include the following sections:\n1. **Blog Purpose**: Describe the main purpose of the blog.\n2. **Key Features**: Highlight features such as dynamic routing and markdown support.\n3. **Tech Stack**: List the technologies used.\n4. **Local Development**: Provide instructions for setting up the project for local development.\n5. **Content Creation**: Explain how to create and manage blog content.\n6. **Deployment**: Include steps for deploying the blog site.",
  "Create a README for a Vue.js admin dashboard. Include the following sections:\n1. **Dashboard Features**: Describe the main features such as user management and data visualization.\n2. **Setup Process**: Provide detailed setup instructions.\n3. **Dependencies**: List the required dependencies.\n4. **Customization**: Explain how to customize and extend the dashboard's functionality.",
  "Write a README for a Dockerized microservices project. Include the following sections:\n1. **Project Architecture**: Describe the project's architecture, including the different microservices and their interactions.\n2. **Docker Environment Setup**: Provide instructions for setting up the Docker environment.\n3. **Running Services**: Explain how to run the microservices.\n4. **Managing Dependencies**: Provide details on managing dependencies and configurations.",
  "Generate a README for a MongoDB-backed social media app. Include the following sections:\n1. **App Purpose**: Explain the purpose and main features of the app.\n2. **MongoDB Integration**: Describe how MongoDB is used for data storage.\n3. **Setup Instructions**: Provide detailed setup instructions.\n4. **Dependencies**: List the required dependencies.\n5. **Running the App**: Include steps for running the app locally and in production.",
];

export function getRandomPrompts(count: number): string[] {
  const shuffled = [...prompts].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}
